import { BRANDING_STATUSES, BUDGETS, CONTENT_STATUSES, FEATURES, MAX_FORM_AGE_MS, MIN_FORM_AGE_MS, PACKAGES, PAGES, PROJECT_TYPES, SERVICES, TIMINGS } from "./constants";
import { LeadError } from "./errors";
import type { Attribution, ClientLeadPayload, LeadSubmissionEnvelope } from "./types";
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const email = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
const clean = (v: unknown, max: number) => typeof v === "string" ? v.replace(/\0/g, "").replace(/[\u0001-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "").trim().replace(/[ \t]{2,}/g, " ").slice(0, max + 1) : "";
const opt = (v: unknown, max: number) => { const s = clean(v, max); return s ? s : undefined; };
const has = (v: string, list: readonly string[]) => list.includes(v);
function req(v: unknown, key: string, min: number, max: number, errs: Record<string, string>) { const s = clean(v, max); if (s.length < min || s.length > max) errs[key] = `Invalid ${key}.`; return s; }
function enumValue(v: unknown, key: string, list: readonly string[], errs: Record<string, string>) { const s = clean(v, 120); if (!has(s, list)) errs[key] = `Invalid ${key}.`; return s; }
function listValue(v: unknown, key: string, allowed: readonly string[], errs: Record<string, string>) { if (!Array.isArray(v) || v.length < 1 || v.length > 20) { errs[key] = `Invalid ${key}.`; return []; } const values = v.map((x) => clean(x, 120)); if (values.some((x) => !has(x, allowed))) errs[key] = `Invalid ${key}.`; return values; }
function website(v: unknown, errs: Record<string, string>) { const s = opt(v, 2048); if (!s) return undefined; try { const u = new URL(s); if (!["http:", "https:"].includes(u.protocol) || ["localhost", "127.0.0.1", "::1"].includes(u.hostname)) errs.website = "Enter a valid public http or https URL."; } catch { errs.website = "Enter a valid public http or https URL."; } return s; }
export function normalizeAttribution(a: unknown): Attribution { const x = (a && typeof a === "object" ? a : {}) as Record<string, unknown>; return { landingPage: opt(x.landingPage, 500), currentPage: opt(x.currentPage, 500), referrer: opt(x.referrer, 500), utmSource: opt(x.utmSource, 500), utmMedium: opt(x.utmMedium, 500), utmCampaign: opt(x.utmCampaign, 500), utmTerm: opt(x.utmTerm, 500), utmContent: opt(x.utmContent, 500), fbclid: opt(x.fbclid, 500), gclid: opt(x.gclid, 500) }; }
export function validateLeadPayload(input: unknown): LeadSubmissionEnvelope { const p = input as ClientLeadPayload; const errs: Record<string, string> = {}; if (!p || typeof p !== "object") throw new LeadError("INVALID_REQUEST", "Invalid request.", 400); if (p.verificationCode) throw new LeadError("SPAM_REJECTED", "Thanks — your request was received successfully.", 200); if (!uuid.test(String(p.submissionId || ""))) errs.submissionId = "Invalid submission."; const age = Date.now() - Date.parse(String(p.formStartedAt || "")); if (!Number.isFinite(age) || age < MIN_FORM_AGE_MS || age > MAX_FORM_AGE_MS) throw new LeadError("SPAM_REJECTED", "Please try submitting the form again.", 403); if (p.formType !== "contact" && p.formType !== "quote") errs.formType = "Invalid form type."; if (p.consent !== true) errs.consent = "Confirm consent and Privacy Policy acknowledgement.";
 const fullName = req(p.contact?.fullName, "fullName", 2, 100, errs); const mail = clean(p.contact?.email, 254).toLowerCase(); if (!email.test(mail) || mail.length > 254) errs.email = "Enter a valid email address."; const phone = opt(p.contact?.phone, 40); const name = req(p.business?.name, "businessName", 1, 150, errs); const site = website(p.business?.website, errs); const industry = opt(p.business?.industry, 120);
 const envelope: LeadSubmissionEnvelope = { schemaVersion: "1.0", submissionId: String(p.submissionId), formType: p.formType === "quote" ? "quote" : "contact", brand: "Website Design Dogs", brandSlug: "website-design-dogs", submittedAt: new Date().toISOString(), source: "website", contact: { fullName, email: mail, ...(phone ? { phone } : {}) }, business: { name, ...(site ? { website: site } : {}), ...(industry ? { industry } : {}) }, enquiry: {}, attribution: normalizeAttribution(p.attribution), consent: { contact: true, privacyPolicyAcknowledged: true, timestamp: new Date().toISOString() } };
 if (p.formType === "contact") { const service = enumValue(p.enquiry?.service, "service", SERVICES, errs); const summary = req(p.enquiry?.summary, "summary", 20, 5000, errs); envelope.enquiry = { service, summary }; }
 if (p.formType === "quote") { envelope.project = { types: listValue(p.project?.types, "types", PROJECT_TYPES, errs), pages: enumValue(p.project?.pages, "pages", PAGES, errs), goal: req(p.project?.goal, "goal", 1, 1000, errs), features: listValue(p.project?.features, "features", FEATURES, errs), contentStatus: enumValue(p.project?.contentStatus, "contentStatus", CONTENT_STATUSES, errs), brandingStatus: enumValue(p.project?.brandingStatus, "brandingStatus", BRANDING_STATUSES, errs), ...(opt(p.project?.existingPlatform, 5000) ? { existingPlatform: opt(p.project?.existingPlatform, 5000) } : {}), notWorking: req(p.project?.notWorking, "notWorking", 10, 5000, errs), accomplish: req(p.project?.accomplish, "accomplish", 10, 5000, errs), ...(opt(p.project?.details, 8000) ? { details: opt(p.project?.details, 8000) } : {}) }; envelope.package = { preferred: enumValue(p.package?.preferred, "preferred", PACKAGES, errs), budget: enumValue(p.package?.budget, "budget", BUDGETS, errs), timing: enumValue(p.package?.timing, "timing", TIMINGS, errs) }; }
 if (Object.keys(errs).length) throw new LeadError("VALIDATION_FAILED", "Please review the highlighted fields and try again.", 400, errs); return envelope; }
