import Image from "next/image";
import Link from "next/link";
import { CookieSettingsButton } from "@/components/consent/cookie-settings-button";
import { siteConfig } from "@/content/site";

export function Breadcrumb({ current }: { current: string }) { return <nav className="mock-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden>›</span><span>{current}</span></nav>; }
export function ScenicHero({ title, current, body, dark, light, home=false }: { title: React.ReactNode; current?: string; body?: string; dark: string; light: string; home?: boolean }) { return <section className={home ? "mock-hero mock-hero--home" : "mock-hero"} data-mockup-hero="integrated-scene"><div className="mock-container mock-hero__grid"><div className="mock-hero__copy">{current ? <Breadcrumb current={current}/> : <p className="mock-eyebrow">LOYAL TO THE GAME.</p>}<h1>{title}</h1>{body ? <p className="mock-lede">{body}</p> : null}{home ? <div className="mock-actions"><Link className="mock-btn" href="/get-started">Get a Free Quote</Link><Link className="mock-btn mock-btn--ghost" href="/portfolio">View Our Work</Link></div> : null}</div><picture className="mock-hero__art"><source srcSet={light} media="(prefers-color-scheme: light)"/><Image src={dark} alt="" fill priority sizes="(min-width: 1024px) 54vw, 100vw" /></picture></div></section>; }
export function CompactFooter() { const year = new Date().getFullYear(); return <footer className="mock-footer" data-full-footer="compact"><div className="mock-container mock-footer__grid"><div><p className="mock-footer__brand">Website Design Dogs</p><p className="mock-footer__small">A service brand of LA CREATIVO GROUP, LLC.</p></div><div><h2>Explore</h2><Link href="/services">Services</Link><Link href="/portfolio">Portfolio</Link><Link href="/packages">Packages</Link><Link href="/faq">FAQ</Link></div><div><h2>Start</h2><Link href="/contact">Project Enquiries</Link><Link href="/get-started">Get a Free Quote</Link><CookieSettingsButton /></div><div><h2>Legal</h2><Link href="/privacy-policy">Privacy Policy</Link><Link href="/terms-and-conditions">Terms</Link><Link href="/refund-cancellation-policy">Refund Policy</Link><Link href="/cookie-policy">Cookie Policy</Link></div></div><div className="mock-container mock-footer__bottom">© {year} {siteConfig.name}. Service brand of {siteConfig.legalOwner}.</div></footer>; }
export function MockPage({ children, footer=true }: { children: React.ReactNode; footer?: boolean }) { return <>{children}{footer ? <CompactFooter/> : null}</>; }
export function CtaStrip(){return <section className="mock-section"><div className="mock-container mock-cta"><div><h2>Ready to start your project?</h2><p>Let’s build a website that drives real results.</p></div><Link className="mock-btn" href="/get-started">Get a Free Quote</Link></div></section>}
