import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo";
import Image from "next/image";
import { FaqAccordion } from "@/components/home/faq-accordion";
import { PortfolioTabs } from "@/components/home/portfolio-tabs";
import { ThemeScene } from "@/components/theme/theme-scene";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Container } from "@/components/ui/container";
import { ArrowRightIcon } from "@/components/ui/icon";
import { Section } from "@/components/ui/section";
import { SectionHeading } from "@/components/ui/section-heading";
import { homeHero, homeServices, industryTiles, packagesHome, reasons, valuePoints } from "@/content/home";

function SceneCard({ darkSrc, lightSrc, alt, className = "aspect-[4/3]" }: { darkSrc: string; lightSrc: string; alt: string; className?: string }) {
  return <Card className="p-3"><ThemeScene darkSrc={darkSrc} lightSrc={lightSrc} alt={alt} width={1400} height={1000} sizes="(max-width: 1024px) 100vw, 42vw" className={className} /></Card>;
}

export const metadata: Metadata = pageMetadata({ title: "Professional Website Design for Growing Businesses", description: "Website Design Dogs creates professional, mobile-ready websites for local and growing businesses with clear packages and dependable support.", path: "/" });
export default function Home() {
  return <>
    <Section className="relative overflow-hidden py-10 sm:py-14 lg:py-16"><Container className="grid min-h-[calc(720px-var(--header-height))] items-center gap-10 lg:grid-cols-[0.95fr_1.05fr]"><div><Badge>{homeHero.eyebrow}</Badge><h1 className="mt-6 max-w-4xl text-5xl font-black tracking-[-0.055em] sm:text-6xl lg:text-7xl">{homeHero.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--color-text-muted)] sm:text-xl">{homeHero.body}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button href="/get-started" size="large" icon={<ArrowRightIcon />} fullWidthMobile>Get a Free Quote</Button><Button href="/portfolio" variant="outline" size="large" fullWidthMobile>View Our Work</Button></div><p className="mt-6 max-w-xl text-sm font-bold text-[var(--color-text-subtle)]">{homeHero.support}</p></div><Card className="p-3 lg:p-4"><ThemeScene darkSrc="/brand/scenes/home-hero-dark.webp" lightSrc="/brand/scenes/home-hero-light.webp" tabletDarkSrc="/brand/crops/tablet/home-dark.webp" tabletLightSrc="/brand/crops/tablet/home-light.webp" mobileDarkSrc="/brand/crops/mobile/home-dark.webp" mobileLightSrc="/brand/crops/mobile/home-light.webp" alt="Website Design Dogs mascot working on a professional website design scene" width={1600} height={1000} priority sizes="(max-width: 768px) 100vw, (max-width: 1024px) 60vw, 50vw" className="aspect-[4/3] sm:aspect-[16/11]" objectPosition="center" /></Card></Container></Section>

    <Section alternate><Container className="grid items-center gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SceneCard darkSrc="/brand/sections/built-local-dark.webp" lightSrc="/brand/sections/built-local-light.webp" alt="Website Design Dogs mascot scene for local business website growth" /><div><SectionHeading eyebrow="BUILT FOR LOCAL BUSINESSES" title="A website partner that understands how local growth works.">Your website should make your business easier to understand, easier to trust, and easier to contact. We combine clear strategy, thoughtful design, and dependable development to help growing businesses compete online.</SectionHeading><div className="mt-8 grid gap-4 sm:grid-cols-2">{valuePoints.map(([title, body]) => <Card key={title} hover className="h-full"><h3 className="text-xl font-black">{title}</h3><p className="mt-3 text-sm text-[var(--color-text-muted)]">{body}</p></Card>)}</div></div></Container></Section>

    <Section><Container><div className="grid items-end gap-8 lg:grid-cols-[1fr_0.42fr]"><SectionHeading eyebrow="OUR SERVICES" title="Everything your website needs to compete and grow.">From the first idea to launch and ongoing care, Website Design Dogs brings the essential pieces together under one dependable team.</SectionHeading><ThemeScene darkSrc="/brand/sections/services-dark.webp" lightSrc="/brand/sections/services-light.webp" alt="Website Design Dogs services mascot scene" width={1200} height={900} sizes="(max-width: 1024px) 100vw, 34vw" className="hidden aspect-[4/3] lg:block" /></div><div className="mt-10 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{homeServices.map(([title, body, icon]) => <Card key={title} hover className="flex h-full flex-col"><Image src={icon} alt="" width={42} height={42} className="h-11 w-11" /><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm text-[var(--color-text-muted)]">{body}</p></Card>)}</div><div className="mt-10 text-center"><Button href="/services" icon={<ArrowRightIcon />}>Explore Our Services</Button></div></Container></Section>

    <Section alternate><Container><SectionHeading className="mx-auto text-center" eyebrow="PORTFOLIO SHOWCASE" title="Website concepts built around real business goals.">Explore a selection of Website Design Dogs concepts created to demonstrate how different industries can communicate clearly, look professional, and convert more effectively.</SectionHeading><PortfolioTabs /><div className="mt-10 text-center"><Button href="/portfolio" icon={<ArrowRightIcon />}>View Full Portfolio</Button></div></Container></Section>

    <Section><Container><div className="grid items-center gap-10 lg:grid-cols-[1fr_0.42fr]"><div><SectionHeading eyebrow="WEBSITE PACKAGES" title="Clear options for different stages of growth.">Choose a practical starting point. Final scope, content requirements, and integrations are confirmed before work begins.</SectionHeading><div className="mt-10 grid gap-5 lg:grid-cols-3">{packagesHome.map(([name, price, label, description, features, href, cta]) => <Card key={name} className={label ? "relative border-[var(--color-primary-orange)]" : ""} hover>{label ? <Badge>{label}</Badge> : null}<h3 className="mt-4 text-2xl font-black">{name}</h3><p className="mt-3 text-4xl font-black">{price}</p><p className="mt-4 text-sm text-[var(--color-text-muted)]">{description}</p><ul className="mt-5 grid gap-3 text-sm text-[var(--color-text-muted)]">{features.map((feature) => <li key={feature} className="flex gap-2"><span className="text-[var(--color-primary-orange)]">•</span>{feature}</li>)}</ul><Button href={href} className="mt-6 w-full" variant={label ? "primary" : "outline"}>{cta}</Button></Card>)}</div><p className="mt-6 text-center text-sm text-[var(--color-text-subtle)]">Exact deliverables, integrations, third-party costs, and timelines are confirmed in the project proposal.</p><div className="mt-8 text-center"><Button href="/packages" variant="secondary">View All Packages</Button></div></div><SceneCard darkSrc="/brand/sections/packages-pricing-dark.webp" lightSrc="/brand/sections/packages-pricing-light.webp" alt="Website Design Dogs packages and pricing scene" /></div></Container></Section>

    <Section alternate><Container><SectionHeading className="mx-auto text-center" eyebrow="LOCAL INDUSTRIES" title="Built for the businesses people rely on every day.">Website Design Dogs creates clear, modern digital experiences for local service providers, professional firms, health and wellness businesses, retailers, and growing companies.</SectionHeading><div className="mt-10 grid grid-cols-2 gap-3 min-[560px]:grid-cols-3 md:grid-cols-5 xl:grid-cols-10">{industryTiles.map(([title, icon]) => <div key={title} className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface-elevated)] p-3 text-center transition hover:-translate-y-0.5 hover:border-[var(--color-primary-orange)]"><Image src={icon} alt="" width={30} height={30} className="mx-auto h-8 w-8" /><p className="mt-2 text-xs font-black leading-5">{title}</p></div>)}</div><div className="mt-9 text-center"><Button href="/get-started" variant="outline">Don’t see your industry? Tell us what you do.</Button></div></Container></Section>

    <Section><Container className="grid items-center gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SceneCard darkSrc="/brand/sections/client-proof-dark.webp" lightSrc="/brand/sections/client-proof-light.webp" alt="Website Design Dogs mascot reviewing a website project" /><div><SectionHeading eyebrow="WHY WEBSITE DESIGN DOGS" title="A clearer, more dependable way to build your website.">A successful website project requires more than attractive screens. It requires clear communication, realistic expectations, thoughtful execution, and reliable follow-through.</SectionHeading><div className="mt-8 grid gap-4 sm:grid-cols-2">{reasons.map(([title, body]) => <Card key={title} hover><h3 className="text-xl font-black">{title}</h3><p className="mt-3 text-sm text-[var(--color-text-muted)]">{body}</p></Card>)}</div></div></Container></Section>

    <Section alternate><Container className="grid items-start gap-10 lg:grid-cols-[1fr_0.42fr]"><div><SectionHeading eyebrow="COMMON QUESTIONS" title="Straight answers before you get started." /><FaqAccordion /><div className="mt-8"><Button href="/faq" variant="outline">View All FAQs</Button></div></div><SceneCard darkSrc="/brand/sections/faq-support-dark.webp" lightSrc="/brand/sections/faq-support-light.webp" alt="Website Design Dogs support and FAQ mascot scene" /></Container></Section>

    <Section className="pb-16 pt-10 lg:pb-20"><Container><div className="grid overflow-hidden rounded-[var(--radius-xl)] border border-[var(--color-border)] bg-[var(--color-surface-elevated)] shadow-[var(--shadow-lg)] lg:grid-cols-[1fr_0.75fr]"><div className="p-7 sm:p-10 lg:p-12"><Badge>LET’S GET STARTED</Badge><h2 className="mt-5 text-4xl font-black tracking-[-0.04em] sm:text-5xl">Ready to put your website to work?</h2><p className="mt-5 max-w-2xl text-lg text-[var(--color-text-muted)]">Tell us about your business, your goals, and what is not working today. We’ll help you identify the right next step without pressure or confusing technical language.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button href="/get-started" size="large" icon={<ArrowRightIcon />} fullWidthMobile>Get a Free Quote</Button><Button href="/contact" variant="outline" size="large" fullWidthMobile>Contact Us</Button></div></div><ThemeScene darkSrc="/brand/sections/cta-dark.webp" lightSrc="/brand/sections/cta-light.webp" alt="Website Design Dogs mascot ready to help with a website project" width={1200} height={900} sizes="(max-width: 1024px) 100vw, 38vw" className="min-h-[320px] rounded-none" /></div></Container></Section>
  </>;
}
