import type { Metadata } from "next";
import Link from "next/link";
import { pageMetadata } from "@/lib/seo";
import { ScenicHero, MockPage } from "@/components/mockup/mockup-components";
export const metadata: Metadata = pageMetadata({ title:"Website Design Dogs", description:"Custom websites for growing businesses.", path:"/" });
const industries=["Home Services","Professional Services","Health & Wellness","Retail","Hospitality","Growing Businesses"];
const services=["Custom Website Design","Website Development","E-Commerce Solutions","SEO & Local Optimization","Website Care"];
const caps=[["5","Core Pages"],["100%","Responsive Layout"],["1","Contact or Quote Form"],["SEO","Foundation Setup"],["CARE","Launch Support"]];
export default function Page(){return <MockPage footer={false}><ScenicHero home title={<>WE DESIGN WEBSITES<br/>THAT DELIVER RESULTS.</>} body="Custom websites that look amazing, work flawlessly, and help your business grow online." dark="/brand/scenes/home-hero-dark.webp" light="/brand/scenes/home-hero-light.webp"/><section className="mock-section"><div className="mock-container"><div className="mock-heading"><p>BUILT FOR LOCAL BUSINESSES</p></div><div className="mock-grid mock-grid--5" style={{gridTemplateColumns:"repeat(6,1fr)"}}>{industries.map(i=><div className="mock-card" key={i}><h3>{i}</h3></div>)}</div></div></section><section className="mock-section"><div className="mock-container"><div className="mock-heading"><p>WHAT WE DO</p><h2>Services That Help Your Business Grow</h2></div><div className="mock-grid mock-grid--5">{services.map(s=><article data-testid="home-service-card" className="mock-card" key={s}><h3>{s}</h3><p>Focused website support for a clearer, faster, and more useful online presence.</p><Link href="/services">Learn More</Link></article>)}</div></div></section><section className="mock-section"><div className="mock-container mock-grid mock-grid--5">{caps.map(([n,l])=><div data-testid="home-capability-tile" className="mock-card" key={l}><p className="price">{n}</p><h3>{l}</h3></div>)}</div></section></MockPage>}
