import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/pages/legal-page";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({
  title: "Privacy Policy",
  description:
    "How Website Design Dogs collects, uses, discloses, protects, and manages website enquiry information.",
  path: "/privacy-policy",
});

const policyGroups: LegalSection[] = [
  {
    id: "scope-controller",
    title: "Scope and Who Is Responsible",
    intro:
      "This policy applies to the Website Design Dogs website, campaign pages, contact forms, and project-brief forms.",
    items: [
      "Website Design Dogs is a service brand of LA CREATIVO GROUP, LLC, which is responsible for the personal information described in this policy.",
      "This policy covers information collected through this website. A separate signed agreement may describe additional project or client data handling.",
      "Privacy questions and requests can be submitted through /contact. Please do not send passwords, payment-card details, government identifiers, or other unnecessary sensitive information.",
    ],
  },
  {
    id: "categories-sources",
    title: "Information We Collect and Its Sources",
    intro:
      "We collect information visitors provide, limited technical data generated by website use, and campaign context needed to understand an enquiry.",
    items: [
      "Contact and business information may include full name, business name, email address, optional phone number, website URL, industry, and existing or preferred platform.",
      "Project information may include requested services, project type, page estimate, goals, features, content and branding status, current challenges, desired outcomes, additional details, package preference, budget range, and timing preference.",
      "Technical and attribution information may include landing page, current page, referrer, selected UTM parameters, fbclid, gclid, consent state, browser or device signals, IP-derived request-security information, and Cloudflare Turnstile verification data.",
      "When marketing consent is granted and Meta services are configured, Meta browser identifiers such as _fbp and _fbc may be processed for conversion attribution.",
      "Information comes directly from visitors, their browser or device, campaign links, security providers, and configured analytics or advertising services.",
    ],
  },
  {
    id: "purposes",
    title: "Why We Use Information",
    intro:
      "We use information only for disclosed business, security, communication, measurement, and legal purposes.",
    items: [
      "We use enquiry information to review requests, contact prospective clients, recommend scope, prepare proposals, preserve campaign context, maintain operational records, and provide requested services.",
      "We use limited technical data to operate forms, prevent spam and abuse, diagnose problems, measure website and campaign performance, maintain consent choices, and protect the website.",
      "We may use records to meet accounting, contractual, dispute-resolution, security, insurance, and legal obligations and to establish, exercise, or defend legal claims.",
      "We do not use website enquiry data for automated decisions that produce legal or similarly significant effects.",
    ],
  },
  {
    id: "disclosures-processors",
    title: "How Information Is Disclosed",
    intro:
      "Information is disclosed only as needed for the purposes described here, for a requested transaction, or when legally required.",
    items: [
      "Submitted enquiries may be routed server-side to Bizosto for lead and enquiry management. Website credentials and API keys are not exposed to visitors.",
      "Service providers may process information for hosting, security, form delivery, analytics, advertising attribution, communications, and business operations. Depending on configuration, these providers may include Vercel, Cloudflare, Google, Meta, and Bizosto.",
      "When marketing consent is granted and the integration is enabled, a successful enquiry may generate a server-side Meta Lead event. Email and optional phone are normalized and cryptographically hashed before transmission, and the event uses the same non-PII event ID as the consent-controlled browser event for deduplication.",
      "Information may be disclosed to professional advisers, authorities, or other parties when reasonably necessary to comply with law, protect rights or safety, investigate misuse, or complete a merger, financing, reorganization, or transfer of business assets subject to appropriate safeguards.",
      "We do not sell personal information for money. Optional advertising technologies may be treated as targeted advertising or sharing under some privacy laws; visitors can decline them through Cookie Settings and supported browser privacy signals.",
    ],
  },
  {
    id: "cookies-tracking",
    title: "Cookies and Similar Technologies",
    intro:
      "Necessary storage supports website operation, while optional analytics and marketing technologies depend on visitor choices and configuration.",
    items: [
      "Google Tag Manager may load to apply consent signals. Analytics storage, advertising storage, ad user data, and ad personalization remain denied until the relevant optional consent is granted.",
      "The wdd-consent-v2 necessary cookie stores consent version, decision time, and category choices for up to 180 days. It does not store form data or direct contact information.",
      "The wdd-attribution-v1 sessionStorage item preserves first-touch campaign context during the browser session and is submitted only when a visitor sends a form.",
      "Configured analytics may include Google Analytics or Microsoft Clarity. Configured marketing technologies may include Google advertising tags or Meta Pixel and Conversions API. Their optional use is controlled by consent.",
      "Cloudflare Turnstile may process technical verification information when configured to distinguish legitimate submissions from abuse.",
    ],
  },
  {
    id: "retention-security",
    title: "Retention and Security",
    intro:
      "We keep information only as long as reasonably necessary for the relevant purpose and apply safeguards appropriate to the information and risk.",
    items: [
      "Enquiry and project records may be retained while a request is active and afterward for legitimate operational, contractual, accounting, tax, security, dispute-resolution, and legal purposes. Retention periods vary by record and applicable obligation.",
      "When information is no longer reasonably needed, it may be deleted, anonymized, or securely disposed of, subject to backup cycles and legal holds.",
      "Safeguards may include HTTPS, server-side secret handling, access controls, validation, honeypot fields, submission timing checks, rate limiting, Cloudflare Turnstile, logging controls, and service-provider security measures.",
      "No internet transmission or storage system is guaranteed to be completely secure. This policy does not claim a legal or security certification.",
      "Service providers may process information in the United States or other locations where they operate, subject to their contractual and legal safeguards.",
    ],
  },
  {
    id: "rights-choices",
    title: "Privacy Rights and Choices",
    intro:
      "Depending on where a visitor lives and which law applies, the visitor may have rights over personal information.",
    items: [
      "Applicable rights may include confirming processing, access, correction, deletion, portability, restriction, objection, and opting out of targeted advertising, sale, sharing, or certain profiling.",
      "Visitors can reject optional technologies, reopen Cookie Settings, or use a supported Global Privacy Control signal. Optional analytics and marketing remain denied when that signal is honored.",
      "Submit a privacy request through /contact and identify the request type. We may verify identity and authority before acting and may retain limited records needed to document the request.",
      "We will respond within the period required by applicable law. Some laws permit an initial response period of 45 days and a reasonable extension with notice.",
      "If a request is denied, the response may explain the reason and any available appeal process. Visitors may appeal through /contact and may contact the appropriate state privacy regulator where applicable.",
      "We do not discriminate against visitors for exercising applicable privacy rights. Legal exceptions may permit or require retention of certain information.",
    ],
  },
  {
    id: "children",
    title: "Children’s Privacy",
    intro:
      "This business-to-business website is not directed to children.",
    items: [
      "We do not knowingly collect personal information from children under 13 through these enquiry forms.",
      "If a parent or guardian believes a child submitted personal information, they should contact us through /contact so the information can be reviewed and deleted where required.",
    ],
  },
  {
    id: "changes",
    title: "Changes to This Policy",
    intro:
      "This policy may be updated as website practices, service providers, or legal requirements change.",
    items: [
      "The Last updated date identifies the current version. Material changes will be presented through an appropriate website notice when required.",
      "Continued use of the website after an update is subject to the revised policy, but changes do not retroactively reduce rights where prohibited by law.",
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Your privacy matters."
      eyebrow="Privacy Policy"
      updated="August 31, 2026"
      intro="How Website Design Dogs collects, uses, discloses, protects, and manages website enquiry information."
      sections={policyGroups}
      darkSrc="/brand/scenes/privacy-hero-dark.webp"
      path="/privacy-policy"
    />
  );
}
