export type Package = { name:string; slug:string; price:string; label?:string; description:string; features:string[]; href:string; cta:string };
export const websitePackages: Package[] = [
{name:"Starter",slug:"starter",price:"$499",description:"A focused professional website for businesses that need a credible online presence.",features:["Up to 5 core pages","Responsive custom layout","Contact or quote form interface","Basic on-page SEO setup","Essential performance optimization","Launch support"],href:"/get-started?package=starter",cta:"Choose Starter"},
{name:"Business",slug:"business",price:"$899",label:"RECOMMENDED",description:"A stronger lead-generation website for established local and service businesses.",features:["Up to 10 core pages","Conversion-focused page structure","Service and location content sections","Analytics-ready implementation","Enhanced performance optimization","30 days of website care"],href:"/get-started?package=business",cta:"Choose Business"},
{name:"Growth",slug:"growth",price:"$1,499",description:"A broader website foundation for businesses preparing to scale marketing and lead generation.",features:["Up to 15 core pages","Advanced lead-generation structure","Blog or content-management setup","Speed and technical optimization","Priority launch support","60 days of website care"],href:"/get-started?package=growth",cta:"Choose Growth"},
];
export const comparisonRows = [["Core pages","Up to 5","Up to 10","Up to 15"],["Responsive design","Included","Included","Included"],["Contact or quote form","Included","Included","Included"],["SEO foundation","Basic","Enhanced","Advanced"],["Conversion-focused structure","Core pages","Expanded","Advanced"],["Service/location sections","Limited","Included","Expanded"],["Content-management setup","Not included","Optional scope","Included where appropriate"],["Performance optimization","Essential","Enhanced","Advanced"],["Website care","Launch support","30 days","60 days"],["Launch support","Included","Included","Priority"]] as const;
export const pricingFactors = ["Additional pages","E-commerce functionality","Full copywriting","Custom illustrations","Complex integrations","Advanced automation","Membership systems","Third-party licensing","Ongoing marketing requirements","Hosting or external platform costs"];
export const packageFaqs = [["Are the listed prices one-time fees?","The listed package prices are starting one-time project fees. Ongoing care, hosting, third-party tools, or additional scope are confirmed separately."],["Is hosting included?","Hosting is not assumed in the package price. Any hosting or external platform cost is documented before work begins."],["Can I add more pages later?","Yes. Additional pages can be scoped during the project or planned as a future improvement."],["Is website content included?","Basic organization is included, but full copywriting, photography, and custom content production may affect the final scope."],["Can you redesign my current website?","Yes. Redesign work starts by reviewing the current site, content, goals, and what needs to improve."],["What happens after launch?","After launch, any included care period begins. Future updates, maintenance, or marketing work can be scoped separately."]] as const;
