export type Service = { title: string; description: string; includes: string[]; icon: string };
export const services: Service[] = [
{ title:"Website Design", icon:"/brand/icons/services/website-design.svg", description:"Custom website layouts created around your business, audience, content, and conversion goals.", includes:["Page structure and information hierarchy","Responsive visual design","Clear calls to action","Brand-aligned styling","Accessibility-conscious layouts"]},
{ title:"Website Development", icon:"/brand/icons/services/development.svg", description:"Reliable website implementation using modern technology, clean structure, and maintainable code.", includes:["Responsive development","Performance-conscious implementation","Reusable components","Technical quality checks","Cross-device compatibility"]},
{ title:"E-Commerce Solutions", icon:"/brand/icons/services/ecommerce.svg", description:"Professional online stores designed to make product discovery, purchasing, and management easier.", includes:["Store layout and product presentation","Shopping and checkout experience","Essential store configuration","Responsive commerce pages","Selected third-party integrations"]},
{ title:"SEO & Local Optimization", icon:"/brand/icons/services/seo-local.svg", description:"Technical and on-page foundations that help search engines understand your website and business.", includes:["Metadata structure","Heading hierarchy","Crawl-friendly page structure","Local service content organization","Performance and mobile readiness"]},
{ title:"Social Media Integration", icon:"/brand/icons/services/social-media.svg", description:"Connect your website with the social platforms and content channels your audience already uses.", includes:["Social profile linking","Share functionality where appropriate","Embedded content where approved","Campaign-ready destination pages","Consistent brand presentation"]},
{ title:"Mobile-Responsive Experiences", icon:"/brand/icons/services/mobile-app.svg", description:"Layouts and interactions designed to remain useful, readable, and conversion-ready across smaller screens.", includes:["Mobile navigation","Responsive content hierarchy","Touch-friendly controls","Mobile form usability","Cross-device testing"]},
{ title:"AI & Workflow Integrations", icon:"/brand/icons/services/ai-automation.svg", description:"Practical integrations and automations that reduce repetitive work and improve customer follow-up.", includes:["Lead-routing preparation","Form workflow planning","CRM integration readiness","Email automation preparation","Operational workflow connections"]},
{ title:"Website Care", icon:"/brand/icons/services/website-care.svg", description:"Ongoing support options that help keep the website secure, current, polished, and useful.", includes:["Content updates","Maintenance reviews","Performance monitoring","Security checks","Improvement planning"]},
];
export const serviceProcess = [
["Discovery","Understand the business, audience, goals, and current challenges."],["Planning","Define the pages, content needs, features, and project scope."],["Design","Create the visual direction, page structure, and responsive experience."],["Development","Build the approved experience using production-ready implementation."],["Review & Launch","Test, refine, confirm details, and prepare the website for release."],["Ongoing Care","Support updates, maintenance, and future improvements where included."],
] as const;
export const clientNeeds = ["A clear business overview","Service and product information","Existing brand materials","Required page content","Timely feedback","Access to approved third-party accounts when required"];
